package com.uaefinancial.tracker.core

import kotlin.test.Test
import com.uaefinancial.tracker.core.CalendarDate
import kotlin.test.assertEquals

/**
 * Statements in layouts and wordings the reader was NOT tuned on: made-up statements in the styles other UAE banks
 * use (key:value blocks, summary boxes, CR / (brackets) / minus / Dr-Cr columns for credits, ISO, "Sep 12, 2026"
 * and no-year dates, dotted leaders, account statements with running balances). Generated by a script so every
 * statement adds up: previous balance + spends - credits = balance.
 */
class StatementReaderUnseenTest {
    private data class Expect(
        val sd: String? = null, val dd: String? = null, val total: Long? = null, val min: Long? = null, val limit: Long? = null,
        val avail: Long? = null, val prev: Long? = null, val n: Int, val deb: Long, val cred: Long, val last4: String?,
        val agree: Boolean, val account: Boolean = false,
    )

    private fun check(name: String, text: String, e: Expect): List<String> {
        val a = StatementReader.analyze(StatementReader.linesFromText(text), 2026)
        val s = a.summary
        val bad = mutableListOf<String>()
        fun cmp(field: String, want: Any?, got: Any?) { if (want != null && want != got) bad += "$name.$field: want $want got $got" }
        cmp("statementDate", e.sd?.let(CalendarDate::parse), s.statementDate)
        cmp("dueDate", e.dd?.let(CalendarDate::parse), s.dueDate)
        cmp("totalDue", e.total, s.totalDueMinor)
        cmp("minimumDue", e.min, s.minimumDueMinor)
        cmp("creditLimit", e.limit, s.creditLimitMinor)
        cmp("available", e.avail, s.availableLimitMinor)
        cmp("previous", e.prev, s.previousBalanceMinor)
        cmp("last4", e.last4, s.cardLast4)
        cmp("isAccount", e.account, s.isAccount)
        cmp("lines", e.n, a.lines.size)
        cmp("spends", e.deb, a.lines.filterNot { it.isCredit }.sumOf { it.amountMinor })
        cmp("credits", e.cred, a.lines.filter { it.isCredit }.sumOf { it.amountMinor })
        cmp("addsUp", e.agree, a.totalsAgree)
        return bad
    }

    private val dib_key_value_block_cr_suffix = """
DUBAI ISLAMIC BANK PJSC
Covered Card Statement

Card Number        : 4567 XXXX XXXX 1234
Statement Date     : 15/09/2026
Payment Due Date   : 10/10/2026
Credit Limit       : AED 30,000.00
Available Limit    : AED 27,397.70
Total Amount Due   : AED 2,602.30
Minimum Amount Due : AED 130.11
Opening Balance    : AED 5,000.00

  Txn Date  Posting Date  Description                           Amount (AED)
  03/09/2026  03/09/2026  CARREFOUR MALL OF THE EMIRATES              452.30
  05/09/2026  06/09/2026  PAYMENT RECEIVED THANK YOU                3,000.00 CR
  08/09/2026  09/09/2026  NOON.COM                                    129.99
  11/09/2026  12/09/2026  REFUND NOON.COM                             129.99 CR
  13/09/2026  13/09/2026  ENOC 1045 AL BARSHA                         150.00
""" to Expect(sd = "2026-09-15", dd = "2026-10-10", total = 260230L, min = 13011L, limit = 3000000L, avail = 2739770L, prev = 500000L, n = 5, deb = 73229L, cred = 312999L, last4 = "1234", agree = true)

    private val emirates_islamic_mon_dates_debit_credit_columns = """
Emirates Islamic
CREDIT CARD STATEMENT

  Statement Closing Date      Payment Due By        Card No.
  05-SEP-26                   30-SEP-26             5299 **** **** 7788

  Previous Statement Balance  Closing Balance       Minimum Payment
  2,100.00                    1,624.00              100.00

  Credit Limit                Available Credit
  15,000.00                   13,376.00

  DATE      DESCRIPTION                                  DEBIT        CREDIT
  12-AUG-26 LULU HYPERMARKET AL QUSAIS                  287.50
  15-AUG-26 PAYMENT - THANK YOU                                     1,500.00
  20-AUG-26 SALIK TOP UP                                100.00
  25-AUG-26 AMAZON.AE RETAIL                            649.00
  27-AUG-26 CASHBACK CREDIT                                            12.50
""" to Expect(sd = "2026-09-05", dd = "2026-09-30", total = 162400L, min = 10000L, limit = 1500000L, avail = 1337600L, prev = 210000L, n = 5, deb = 103650L, cred = 151250L, last4 = "7788", agree = true)

    private val rakbank_summary_box_parentheses_credits = """
RAKBANK
Credit Card Statement

  Statement Date          16/09/2026
  Due Date                11/10/2026
  Card Number             4029 12XX XXXX 5566

  Previous Balance  Payments & Credits    Purchases & Debits    New Balance
  4,000.00          (2,815.00)            2,004.25              3,189.25

  Total Due               3,189.25        Minimum Due           159.46
  Credit Limit            20,000.00       Available Credit Limit  16,810.75

  Date      Transaction Details                             Amount AED
  01/09/26  TALABAT DUBAI                                        89.50
  04/09/26  PAYMENT RECEIVED                                 (2,500.00)
  06/09/26  ETISALAT BILL PAYMENT                               399.00
  09/09/26  ANNUAL FEE                                          315.00
  10/09/26  FEE REVERSAL                                       (315.00)
  14/09/26  DUBAI DUTY FREE                                   1,200.75
""" to Expect(sd = "2026-09-16", dd = "2026-10-11", total = 318925L, min = 15946L, limit = 2000000L, avail = 1681075L, prev = 400000L, n = 6, deb = 200425L, cred = 281500L, last4 = "5566", agree = true)

    private val cbd_word_dates_trailing_minus = """
Commercial Bank of Dubai
Your credit card statement

  Stmt Date         Sep 12, 2026
  Pay By            Oct 07, 2026
  Previous Balance  1,500.00
  Amount Due        816.59
  Min. Payment Due  100.00
  Credit Line       25,000.00
  Available Credit Line 24,183.41
Card ending ****4411

  Transaction Date  Description                                   Amount
  Aug 18            SPINNEYS JUMEIRAH                             234.10
  Aug 22            PAYMENT - ONLINE BANKING                    1,000.00-
  Aug 29            APPLE.COM/BILL                                 36.99
  Sep 02            UBER TRIP                                      45.50
""" to Expect(sd = "2026-09-12", dd = "2026-10-07", total = 81659L, min = 10000L, limit = 2500000L, avail = 2418341L, prev = 150000L, n = 4, deb = 31659L, cred = 100000L, last4 = "4411", agree = true)

    private val citi_iso_dates_leading_minus = """
Citibank N.A. UAE
Citi Credit Card

  Statement Closing Date:     2026-09-10
  Payment Due Date:           2026-10-05
  Previous Balance:           2,500.00
  New Balance:                2,068.00
  Minimum Payment Due:        125.00
  Credit Limit:               40,000.00
  Available Credit:           37,932.00
Account number ending in 9021

  Date        Description                                   Amount (AED)
  2026-08-14  MARKS & SPENCER DUBAI                               312.00
  2026-08-20  PAYMENT THANK YOU                                -2,000.00
  2026-08-28  BOOKING.COM                                       1,456.00
  2026-09-01  MERCHANT CREDIT BOOKING.COM                        -200.00
""" to Expect(sd = "2026-09-10", dd = "2026-10-05", total = 206800L, min = 12500L, limit = 4000000L, avail = 3793200L, prev = 250000L, n = 4, deb = 176800L, cred = 220000L, last4 = "9021", agree = true)

    private val stanchart_separate_dr_cr_column = """
Standard Chartered Bank
Credit Card Statement

  Statement Date                  12 Sep 2026
  Payment Due Date                07 Oct 2026
  Statement Balance               1,256.05
  Minimum Amount Payable          100.00
  Previous Balance                1,200.00
  Credit Limit                    18,000.00
Card Number 5543-XXXX-XXXX-3301

  Date        Transaction Description                       Amount    Dr/Cr
  02 Sep 2026 GEANT HYPERMARKET                             415.75    DR
  04 Sep 2026 PAYMENT RECEIVED                              900.00    CR
  07 Sep 2026 DEWA                                          512.30    DR
  09 Sep 2026 STARBUCKS DXB MALL                             28.00    DR
""" to Expect(sd = "2026-09-12", dd = "2026-10-07", total = 125605L, min = 10000L, limit = 1800000L, prev = 120000L, n = 4, deb = 95605L, cred = 90000L, last4 = "3301", agree = true)

    private val adib_islamic_wording_particulars = """
Abu Dhabi Islamic Bank
Card Statement

  Card Limit              Available Balance         Total Outstanding Amount
  10,000.00               7,120.55                  2,879.45
  Minimum Payment Amount  Last Date of Payment      Statement Date
  150.00                  05 Oct 2026               14 Sep 2026
  Previous Balance        950.00
Card No: 4213 XXXX XXXX 0098

  Trans. Date Value Date    Particulars                          Debit        Credit
  01 Sep 2026 02 Sep 2026   NESTO HYPERMARKET SHARJAH           180.45
  03 Sep 2026 03 Sep 2026   PAYMENT VIA ADIB MOBILE                           750.00
  06 Sep 2026 07 Sep 2026   SHARAF DG                         2,499.00
""" to Expect(sd = "2026-09-14", dd = "2026-10-05", total = 287945L, min = 15000L, limit = 1000000L, avail = 712055L, prev = 95000L, n = 3, deb = 267945L, cred = 75000L, last4 = "0098", agree = true)

    private val nbf_foreign_currency_columns = """
National Bank of Fujairah
Credit Card Statement

  Statement Date        Payment Due Date        Total Amount Due      Minimum Amount Due
  05/09/2026            30/09/2026              1,637.50              100.00
  Previous Balance      800.00                  Credit Limit          12,000.00
Card Number: 5412 34** **** 7002

  Date      Description                    Original Amount  Currency      Amount (AED)
  12/08/2026  HOTEL PARIS OPERA                     250.00  EUR               1,075.00
  15/08/2026  PAYMENT RECEIVED - THANK YOU          500.00  AED                 500.00 CR
  18/08/2026  AMAZON UK                              30.00  GBP                 142.50
  20/08/2026  ADNOC 332                             120.00  AED                 120.00
""" to Expect(sd = "2026-09-05", dd = "2026-09-30", total = 163750L, min = 10000L, limit = 1200000L, prev = 80000L, n = 4, deb = 133750L, cred = 50000L, last4 = "7002", agree = true)

    private val liv_account_withdrawal_deposit_balance = """
Liv. by Emirates NBD
Account Statement

Account Number: 1015 2233 4455 6677
Statement Period: 01/08/2026 to 31/08/2026

  Opening Balance             12,000.00
  Closing Balance             16,512.50

  Date      Narration                             Withdrawal       Deposit         Balance
  01/08/2026  SALARY AUG 2026                                    15,000.00       27,000.00
  03/08/2026  RENT CHEQUE 000123                    7,000.00                     20,000.00
  05/08/2026  ATM WITHDRAWAL DXB                      500.00                     19,500.00
  10/08/2026  TRANSFER TO CARD 1234                 3,000.00                     16,500.00
  15/08/2026  INTEREST CREDIT                                        12.50       16,512.50
""" to Expect(sd = "2026-08-31", prev = 1200000L, n = 5, deb = 1050000L, cred = 1501250L, last4 = "6677", agree = true, account = true)

    private val wio_account_signed_amounts_running_balance = """
Wio Bank PJSC
Statement of Account

Account No. 9876 5432 1098
Period from 01 Aug 2026 to 31 Aug 2026

  Opening Balance       AED 3,000.00
  Closing Balance       AED 15,515.00

  Date        Description                                 Amount         Balance
  02 Aug 2026 DEWA BILL                                  -450.00        2,550.00
  05 Aug 2026 SALARY CREDIT                           +12,500.00       15,050.00
  09 Aug 2026 CAREEM                                      -35.00       15,015.00
  12 Aug 2026 INWARD REMITTANCE                        +2,000.00       17,015.00
  20 Aug 2026 CARD PAYMENT                             -1,500.00       15,515.00
""" to Expect(sd = "2026-08-31", prev = 300000L, n = 5, deb = 198500L, cred = 1450000L, last4 = "1098", agree = true, account = true)

    private val mashreq_neo_account_cr_balances = """
Mashreq Neo
Account Statement

A/C No. 0199 8877 6601
Statement from 01/09/2026 to 30/09/2026

  Balance Brought Forward     800.00 Cr

  Value Date  Transaction Details                    Debit        Credit           Balance
  03/09/2026  POS PURCHASE LULU                     120.50                          679.50 Cr
  06/09/2026  IPP TRANSFER FROM AHMED                             500.00          1,179.50 Cr
  09/09/2026  SERVICE CHARGE                         26.25                        1,153.25 Cr
  Closing Balance                                                                 1,153.25 Cr
""" to Expect(sd = "2026-09-30", prev = 80000L, n = 3, deb = 14675L, cred = 50000L, last4 = "6601", agree = true, account = true)

    private val ajman_no_year_dates_wrapped_descriptions = """
Ajman Bank
Credit Card Statement - September 2026

  Statement Date              06 SEP 2026
  Payment Due Date            01 OCT 2026
  Total Amount Due            3,209.99
  Minimum Amount Due          153.00
  Previous Balance            1,200.00
Card 4321 XXXX XXXX 8080

  Date    Description                                           Amount
  14 AUG  AMAZON MARKETPLACE                                    159.99
          ORDER 402-1234567
  16 AUG  PAYMENT RECEIVED                                    1,000.00 CR
  21 AUG  EMIRATES AIRLINE                                    2,850.00
          TICKET 176-2233445566
""" to Expect(sd = "2026-09-06", dd = "2026-10-01", total = 320999L, min = 15300L, prev = 120000L, n = 3, deb = 300999L, cred = 100000L, last4 = "8080", agree = true)

    private val sib_dotted_leaders = """
Sharjah Islamic Bank
Card Statement

Statement Date ...................... 13/09/2026
Payment Due Date .................... 08/10/2026
Previous Balance .................... 300.00
Total Amount Due .................... 270.00
Minimum Amount Due .................. 100.00
Credit Limit ........................ 5,000.00
Card Number ......................... 4400 XXXX XXXX 5151

  Date      Details                                    Debit        Credit
  02/09/2026  CARREFOUR                                50.00
  08/09/2026  PAYMENT                                               200.00
  11/09/2026  VOX CINEMAS                             120.00
""" to Expect(sd = "2026-09-13", dd = "2026-10-08", total = 27000L, min = 10000L, limit = 500000L, prev = 30000L, n = 3, deb = 17000L, cred = 20000L, last4 = "5151", agree = true)

    private val uab_aed_prefix_in_cells = """
UAB United Arab Bank
Credit Card Statement

  Statement Date          15-09-2026
  Due Date                10-10-2026
  Outstanding Balance     AED 266.99
  Minimum Due             AED 50.00
  Previous Balance        AED 600.00
Card ending 2468

  Date        Merchant                                      Amount
  03-09-2026  SPOTIFY                                    AED 21.99
  05-09-2026  PAYMENT RECEIVED                          AED 400.00 CR
  07-09-2026  KFC                                        AED 45.00
""" to Expect(sd = "2026-09-15", dd = "2026-10-10", total = 26699L, min = 5000L, prev = 60000L, n = 3, deb = 6699L, cred = 40000L, last4 = "2468", agree = true)

    private val arab_bank_prose_and_payment_slip = """
Arab Bank
Credit Card Statement

  Statement Date          12/09/2026
  Payment Due Date        07/10/2026
  Total Payment Due       1,099.00
  Minimum Payment Due     100.00
  Previous Balance        700.00
Card Number 5210 XXXX XXXX 1357
If you pay only the minimum payment due of 100.00 each month, it will take you longer to pay off your balance.

  Date      Description                                   Amount (AED)
  01/09/2026  IKEA DUBAI                                        899.00
  04/09/2026  PAYMENT THANK YOU                                 500.00 CR

PAYMENT SLIP
  Total Payment Due       1,099.00
  Amount Paid             ..........
""" to Expect(sd = "2026-09-12", dd = "2026-10-07", total = 109900L, min = 10000L, prev = 70000L, n = 2, deb = 89900L, cred = 50000L, last4 = "1357", agree = true)

    private val investbank_charges_payments_columns = """
InvestBank
Credit Card Statement

  Statement Date          15.09.2026
  Due Date                10.10.2026
  Current Balance         112.00
  Minimum Due             25.00
  Previous Balance        100.00
Card 4000 00XX XXXX 9191

  Date        Description                              Charges        Payments
  05.09.2026  GYM MEMBERSHIP                            350.00
  07.09.2026  PAYMENT                                                   350.00
  12.09.2026  PARKING RTA                                12.00
""" to Expect(sd = "2026-09-15", dd = "2026-10-10", total = 11200L, min = 2500L, prev = 10000L, n = 3, deb = 36200L, cred = 35000L, last4 = "9191", agree = true)

    private val all = listOf("dib_key_value_block_cr_suffix" to dib_key_value_block_cr_suffix, "emirates_islamic_mon_dates_debit_credit_columns" to emirates_islamic_mon_dates_debit_credit_columns, "rakbank_summary_box_parentheses_credits" to rakbank_summary_box_parentheses_credits, "cbd_word_dates_trailing_minus" to cbd_word_dates_trailing_minus, "citi_iso_dates_leading_minus" to citi_iso_dates_leading_minus, "stanchart_separate_dr_cr_column" to stanchart_separate_dr_cr_column, "adib_islamic_wording_particulars" to adib_islamic_wording_particulars, "nbf_foreign_currency_columns" to nbf_foreign_currency_columns, "liv_account_withdrawal_deposit_balance" to liv_account_withdrawal_deposit_balance, "wio_account_signed_amounts_running_balance" to wio_account_signed_amounts_running_balance, "mashreq_neo_account_cr_balances" to mashreq_neo_account_cr_balances, "ajman_no_year_dates_wrapped_descriptions" to ajman_no_year_dates_wrapped_descriptions, "sib_dotted_leaders" to sib_dotted_leaders, "uab_aed_prefix_in_cells" to uab_aed_prefix_in_cells, "arab_bank_prose_and_payment_slip" to arab_bank_prose_and_payment_slip, "investbank_charges_payments_columns" to investbank_charges_payments_columns)

    @Test fun every_unseen_layout_is_read_correctly() {
        val problems = all.flatMap { (name, c) -> check(name, c.first, c.second) }
        println("UNSEEN LAYOUTS: ${all.size - problems.map { it.substringBefore('.') }.distinct().size}/${all.size} fully right, ${problems.size} wrong fields")
        problems.forEach { println("  $it") }
        assertEquals(emptyList(), problems)
    }
}
