package com.uaefinancial.tracker.core

import org.junit.Test
import java.time.LocalDate
import kotlin.test.assertEquals

/**
 * A second, held-out set of layouts, written after the reader was improved on StatementReaderUnseenTest and run before any further change: made-up statements in the styles other UAE banks
 * use (key:value blocks, summary boxes, CR / (brackets) / minus / Dr-Cr columns for credits, ISO, "Sep 12, 2026"
 * and no-year dates, dotted leaders, account statements with running balances). Generated by a script so every
 * statement adds up: previous balance + spends - credits = balance.
 */
class StatementReaderHeldOutTest {
    private data class Expect(
        val sd: String? = null, val dd: String? = null, val total: Long? = null, val min: Long? = null, val limit: Long? = null,
        val avail: Long? = null, val prev: Long? = null, val n: Int, val deb: Long, val cred: Long, val last4: String?,
        val agree: Boolean, val account: Boolean = false,
    )

    private fun check(name: String, text: String, e: Expect): List<String> {
        val a = StatementReader.analyze(StatementReader.linesFromText(text), 2026)
        val s = a.summary
        val bad = mutableListOf<String>()
        fun cmp(field: String, want: Any?, got: Any?) { if (want != null && want != got) bad += "$name.$field: want $want got $got" }
        cmp("statementDate", e.sd?.let(LocalDate::parse), s.statementDate)
        cmp("dueDate", e.dd?.let(LocalDate::parse), s.dueDate)
        cmp("totalDue", e.total, s.totalDueMinor)
        cmp("minimumDue", e.min, s.minimumDueMinor)
        cmp("creditLimit", e.limit, s.creditLimitMinor)
        cmp("available", e.avail, s.availableLimitMinor)
        cmp("previous", e.prev, s.previousBalanceMinor)
        cmp("last4", e.last4, s.cardLast4)
        cmp("isAccount", e.account, s.isAccount)
        cmp("lines", e.n, a.lines.size)
        cmp("spends", e.deb, a.lines.filterNot { it.isCredit }.sumOf { it.amountMinor })
        cmp("credits", e.cred, a.lines.filter { it.isCredit }.sumOf { it.amountMinor })
        cmp("addsUp", e.agree, a.totalsAgree)
        return bad
    }

    private val h1_unmarked_credits_please_pay_by = """
Emirates NBD
Visa Credit Card Statement

  Statement Date              14/09/2026
  Please pay by               09/10/2026
  Closing Statement Balance   720.50
  Minimum Payment Required    50.00
  Previous Balance            900.00
Card XXXX-XXXX-XXXX-1234

  Date      Description                                         Amount
  02/09/2026  ZARA DUBAI MALL                                   450.00
  05/09/2026  PAYMENT RECEIVED - THANK YOU                      600.00
  09/09/2026  CARREFOUR                                         120.50
  12/09/2026  REFUND ZARA                                       150.00
""" to Expect(sd = "2026-09-14", dd = "2026-10-09", total = 72050L, min = 5000L, prev = 90000L, n = 4, deb = 57050L, cred = 75000L, last4 = "1234", agree = true)

    private val h2_account_minus_means_out_no_balance_column = """
Zand Bank
Account Statement

Account Number 5566 7788 9900 1122
Statement period 01/08/2026 - 31/08/2026

  Opening Balance             1,000.00
  Closing Balance             9,729.50

  Date      Details                                             Amount
  01/08/2026  SALARY                                          9,000.00
  04/08/2026  DEWA                                             -320.00
  09/08/2026  NOON                                             -150.50
  15/08/2026  TRANSFER FROM FRIEND                              200.00
""" to Expect(sd = "2026-08-31", prev = 100000L, n = 4, deb = 47050L, cred = 920000L, last4 = "1122", agree = true, account = true)

    private val h3_squeezed_aed_and_Cr = """
Dubai First
Card Statement

  Statement Date          10 Sep 2026
  Payment Due Date        05 Oct 2026
  Total Amount Due        AED465.00
  Minimum Amount Due      AED42.00
  Previous Balance        AED500.00
Card Number 5500 00** **** 4321

  Date        Description                                   Amount
  03 Sep 2026 UBER                                        AED45.00
  06 Sep 2026 PAYMENT                                    AED300.00 Cr
  08 Sep 2026 H&M                                        AED220.00
""" to Expect(sd = "2026-09-10", dd = "2026-10-05", total = 46500L, min = 4200L, prev = 50000L, n = 3, deb = 26500L, cred = 30000L, last4 = "4321", agree = true)

    private val h4_year_end_no_year_dates = """
HSBC Bank Middle East
Credit Card Statement

  Statement Date              12/01/2027
  Payment Due Date            06/02/2027
  Statement Balance           780.00
  Minimum Payment Due         35.00
  Previous Balance            600.00
Card Number 4000 12** **** 7777

  Date    Transaction Details                             Amount (AED)
  20/12   NEW YEAR GIFTS                                        500.00
  28/12   PAYMENT RECEIVED                                      400.00 CR
  03/01   CARREFOUR                                              80.00
""" to Expect(sd = "2027-01-12", dd = "2027-02-06", total = 78000L, min = 3500L, prev = 60000L, n = 3, deb = 58000L, cred = 40000L, last4 = "7777", agree = true)

    private val h5_two_pages_carried_forward = """
CBI Commercial Bank International
Credit Card Statement

  Statement Date              12/09/2026
  Payment Due Date            07/10/2026
  Total Amount Due            500.00
  Minimum Amount Due          25.00
  Previous Balance            400.00
Card Number 4111 11XX XXXX 2020

  Date      Description                                Debit        Credit
  01/09/2026  ITEM ONE SHOP                           100.00
  02/09/2026  ITEM TWO SHOP                           200.00
            Balance carried forward                   700.00
Page 1 of 2

CBI Commercial Bank International
Credit Card Statement (continued)
  Date      Description                                Debit        Credit
            Balance brought forward                   700.00
  05/09/2026  PAYMENT RECEIVED                                      250.00
  07/09/2026  ITEM THREE SHOP                          50.00
""" to Expect(sd = "2026-09-12", dd = "2026-10-07", total = 50000L, min = 2500L, prev = 40000L, n = 4, deb = 35000L, cred = 25000L, last4 = "2020", agree = true)

    private val h6_account_reference_column_opening_row = """
Al Masraf
Statement of Account

Account No 0012 3456 7890
From 01/09/2026 To 30/09/2026

  Date      Reference     Description                    Debit        Credit         Balance
                          OPENING BALANCE                                             500.00
  02/09/2026  FT26245001  ATM CASH                      200.00                        300.00
  05/09/2026  FT26248002  CHEQUE DEPOSIT                            1,500.00        1,800.00
  09/09/2026  FT26252003  ONLINE TRANSFER               600.00                      1,200.00
                          CLOSING BALANCE                                           1,200.00
""" to Expect(sd = "2026-09-30", prev = 50000L, n = 3, deb = 80000L, cred = 150000L, last4 = "7890", agree = true, account = true)

    private val h7_undated_totals_under_table = """
ADCB
Credit Card Statement

  Statement Date              13/09/2026
  Payment Due Date            08/10/2026
  Total Amount Due            300.00
  Minimum Amount Due          15.00
  Previous Balance            200.00
Card Number 5200 XXXX XXXX 6060

  Date      Description                                   Amount (AED)
  04/09/2026  IKEA                                              400.00
  06/09/2026  PAYMENT THANK YOU                                 300.00 CR
            Total Purchases                                     400.00
            Total Payments                                      300.00 CR
""" to Expect(sd = "2026-09-13", dd = "2026-10-08", total = 30000L, min = 1500L, prev = 20000L, n = 2, deb = 40000L, cred = 30000L, last4 = "6060", agree = true)

    private val h8_label_grid_three_columns = """
RAKBANK
Titanium Card Statement

  Statement Date              Payment Due Date              Total Amount Due
  15-09-2026                  10-10-2026                    225.00
  Minimum Amount Due          Previous Balance              Credit Limit
  11.00                       300.00                        7,000.00
Card No. 4520 XXXX XXXX 3434

  Transaction Date  Description                                     Amount
  11-09-2026        STARBUCKS                                        25.00
  12-09-2026        PAYMENT RECEIVED                                100.00 CR
""" to Expect(sd = "2026-09-15", dd = "2026-10-10", total = 22500L, min = 1100L, limit = 700000L, prev = 30000L, n = 2, deb = 2500L, cred = 10000L, last4 = "3434", agree = true)

    private val h9_foreign_amount_next_line = """
Mashreq
Credit Card Statement

  Statement Date              12/09/2026
  Payment Due Date            07/10/2026
  Total Amount Due            675.00
  Minimum Amount Due          10.00
  Previous Balance            200.00
Card Number 4600 XXXX XXXX 4680

  Date      Description                                   Amount (AED)
  05/09/2026  AMAZON UK MARKETPLACE
            GBP 100.00 @ 4.70                                   470.00
  08/09/2026  TALABAT                                             5.00
""" to Expect(sd = "2026-09-12", dd = "2026-10-07", total = 67500L, min = 1000L, prev = 20000L, n = 2, deb = 47500L, cred = 0L, last4 = "4680", agree = true)

    private val h10_credit_column_before_debit = """
Ruya Bank
Account Statement

Account Number 3322 1100 5544
Period: 01/09/2026 to 30/09/2026

  Opening Balance             100.00
  Closing Balance             2,800.00

  Date      Description                               Credit         Debit         Balance
  02/09/2026  SALARY                                5,000.00                      5,100.00
  04/09/2026  RENT                                                2,000.00        3,100.00
  06/09/2026  GROCERIES                                             300.00        2,800.00
""" to Expect(sd = "2026-09-30", prev = 10000L, n = 3, deb = 230000L, cred = 500000L, last4 = "5544", agree = true, account = true)

    private val all = listOf("h1_unmarked_credits_please_pay_by" to h1_unmarked_credits_please_pay_by, "h2_account_minus_means_out_no_balance_column" to h2_account_minus_means_out_no_balance_column, "h3_squeezed_aed_and_Cr" to h3_squeezed_aed_and_Cr, "h4_year_end_no_year_dates" to h4_year_end_no_year_dates, "h5_two_pages_carried_forward" to h5_two_pages_carried_forward, "h6_account_reference_column_opening_row" to h6_account_reference_column_opening_row, "h7_undated_totals_under_table" to h7_undated_totals_under_table, "h8_label_grid_three_columns" to h8_label_grid_three_columns, "h9_foreign_amount_next_line" to h9_foreign_amount_next_line, "h10_credit_column_before_debit" to h10_credit_column_before_debit)

    @Test fun held_out_layouts_are_read_correctly() {
        val problems = all.flatMap { (name, c) -> check(name, c.first, c.second) }
        println("HELD-OUT LAYOUTS: ${all.size - problems.map { it.substringBefore('.') }.distinct().size}/${all.size} fully right, ${problems.size} wrong fields")
        problems.forEach { println("  $it") }
        assertEquals(emptyList(), problems)
    }
}
