"""
Turns the .tsv statement fixtures (see statement_fixtures_round*.py) into a Kotlin source file, so the blind
PDF tests run in shared common code: on the JVM for Android and on the iPhone simulator.
Usage: python3 tools/embed_statement_fixtures.py <dir with .tsv files> <output .kt>
"""
import glob, os, sys

src, out = sys.argv[1], sys.argv[2]
entries = []
for path in sorted(glob.glob(os.path.join(src, "*.tsv"))):
    name = os.path.basename(path)[:-4]
    text = open(path, encoding="utf-8").read()
    assert '"""' not in text
    text = text.replace("$", "${'$'}")
    entries.append((name, text))
with open(out, "w", encoding="utf-8") as f:
    f.write("package com.uaefinancial.tracker.core\n\n")
    f.write("// GENERATED by tools/embed_statement_fixtures.py from the blind PDF statements. Do not edit by hand.\n")
    f.write("// Each: #expected=value lines, then one glyph per line: page, x, y, width, size, text (tab separated).\n\n")
    f.write("internal object StatementFixtures {\n")
    f.write("    val all: Map<String, String> by lazy {\n        mapOf(\n")
    for name, _ in entries:
        f.write(f'            "{name}" to {name.upper()},\n')
    f.write("        )\n    }\n")
    for name, text in entries:
        f.write(f'\n    private val {name.upper()} = """{text}"""\n')
    f.write("}\n")
print(len(entries), "fixtures")
