"""
Turns a REAL bank statement PDF into a glyph fixture for the statement reader tests, with personal details blanked.
Usage: python3 -I tools/embed_real_statement.py <statement.pdf> <name> <pages e.g. 0,2,3> <out.kt> key=value ...
The glyphs are what the phone's PDF reader (PdfBox) gives the app: page, x, y (baseline from top), width, size, text.
Names, addresses, card and account numbers are replaced by X / 0 before anything is written; amounts and dates stay.
Needs: pip install pdfminer.six
"""
import re, sys
from pdfminer.high_level import extract_pages
from pdfminer.layout import LTChar

pdf, name, pages, out = sys.argv[1], sys.argv[2], [int(p) for p in sys.argv[3].split(",")], sys.argv[4]
expect = [a for a in sys.argv[5:] if "=" in a]
# Rows are matched with the spaces removed (blank glyphs are dropped), so these patterns have no spaces.
SCRUB = [r"MS\.[A-Z]+[A-Z]+", r"DR[A-Z]+BUILDING", r"P\.O\.BOX\d+", r"DUBAI,ARE", r"CARDNO\.[\dX]+[A-Z]+",
         r"5196\d*X*\d{4}", r"Account#\d+", r"MEHWISH", r"ANNUM", r"MOSTAFA", r"BUILDING"]

def walk(o, acc):
    if isinstance(o, LTChar): acc.append(o)
    elif hasattr(o, "__iter__"):
        for c in o: walk(c, acc)

all_glyphs = []
for pno, page in enumerate(extract_pages(pdf)):
    if pno not in pages: continue
    chars = []; walk(page, chars)
    H = page.height
    g = [[pages.index(pno), round(c.x0, 2), round(H - c.matrix[5], 2), round(c.adv, 2), round(c.size, 2), c.get_text()]
         for c in chars if c.get_text().strip()]
    # blank personal details: rows by baseline, then regexes over the row text in x order
    g.sort(key=lambda r: (r[2], r[1]))
    rows = []
    for r in g:
        if rows and abs(rows[-1][0][2] - r[2]) <= 2.0: rows[-1].append(r)
        else: rows.append([r])
    for row in rows:
        row.sort(key=lambda r: r[1])
        text = "".join(r[5] for r in row)
        for pat in SCRUB:
            for m in re.finditer(pat, text):
                for r in row[m.start():m.end()]:
                    if r[5].isdigit(): r[5] = "0"
                    elif r[5].isalpha() and r[5].isascii(): r[5] = "X"
    all_glyphs += g

lines = ["#" + e for e in expect] + ["\t".join(str(v) for v in r) for r in all_glyphs]
chunks, cur, size = [], [], 0
for ln in lines:
    b = len(ln.encode()) + 1
    if size + b > 40000: chunks.append("\n".join(cur) + "\n"); cur, size = [], 0
    cur.append(ln); size += b
chunks.append("\n".join(cur) + "\n")
with open(out, "w", encoding="utf-8") as f:
    f.write("package com.uaefinancial.tracker.core\n\n")
    f.write("// GENERATED by tools/embed_real_statement.py from a real statement (personal details blanked). Do not edit by hand.\n")
    f.write("// Split in pieces: one string constant may not exceed 64 KB in a class file.\n\n")
    f.write("internal object RealStatementFixtures {\n")
    f.write(f'    val {name}: String by lazy {{ listOf({", ".join(f"P{i}" for i in range(len(chunks)))}).joinToString("") }}\n')
    for i, c in enumerate(chunks):
        c = c.replace("$", "${'$'}")
        assert '"""' not in c
        f.write(f'    private val P{i} = """{c}"""\n')
    f.write("}\n")
print(len(all_glyphs), "glyphs,", len(chunks), "pieces")
